// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgk-bPW7VKpYB_iQCZve64r9q6xmI6W34',
    appId: '1:668754273407:web:e5d504abcbc2d58794cb4a',
    messagingSenderId: '668754273407',
    projectId: 'drbot-app',
    authDomain: 'drbot-app.firebaseapp.com',
    storageBucket: 'drbot-app.firebasestorage.app',
    measurementId: 'G-7KK7VK7NND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsr7coY0tWItEaOe725OdK7Jvtig9OSi0',
    appId: '1:668754273407:android:5562ed3a09d98a6094cb4a',
    messagingSenderId: '668754273407',
    projectId: 'drbot-app',
    storageBucket: 'drbot-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgTa1EfiqQ5ml0Hp14RtCrINvoCt3JkIk',
    appId: '1:668754273407:ios:1ac162f858076a5d94cb4a',
    messagingSenderId: '668754273407',
    projectId: 'drbot-app',
    storageBucket: 'drbot-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgTa1EfiqQ5ml0Hp14RtCrINvoCt3JkIk',
    appId: '1:668754273407:ios:1ac162f858076a5d94cb4a',
    messagingSenderId: '668754273407',
    projectId: 'drbot-app',
    storageBucket: 'drbot-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgk-bPW7VKpYB_iQCZve64r9q6xmI6W34',
    appId: '1:668754273407:web:442f0e9f85b9bb9994cb4a',
    messagingSenderId: '668754273407',
    projectId: 'drbot-app',
    authDomain: 'drbot-app.firebaseapp.com',
    storageBucket: 'drbot-app.firebasestorage.app',
    measurementId: 'G-Q77H01P38G',
  );
}
